[package]
name = "Copy-right"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-s3 = "1.120.0"
aws-sdk-s3control = "1.107.0"
dotenvy = "0.15.7"
tokio = { version = "1.49.0", features = ["full"] }
