name = "video-upload-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-27"

[build]
command = "cargo install -q worker-build && worker-build --release"


# Bindings allow you to access resources directly
[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "copy-right"

[[d1_databases]]
binding = "DB"
database_name = "copyright"
database_id = "c296de5f-5e74-44b1-bbbf-c48bbea1f2cd" # Run 'wrangler d1 info video-db' to get this
